---
title: "Data analysis-2026/02/22"
author: "Jicong Zhang"
date: "2026-02-23"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(ggridges)
library(ggplot2)
library(modelr)
library(mgcv)
library(dplyr)
library(readr)
library(gtsummary)
set.seed(1)
knitr::opts_chunk$set(
  fig.width = 9,
  fig.asp = .6,
  out.width = "100%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
# Data input
wastewater = read.csv("./Data/wastewater.csv") %>%
  janitor::clean_names() %>%
  rename(wrrf = wrrf_name,
         abbreviation = wrrf_abbreviation,
         concentration = concentration_sars_co_v_2_gene_target_n1_copies_l,
         population = population_served_estimated,
         per_Sars_load = per_capita_sars_co_v_2_load_n1_copies_per_day_per_population) %>%
  select(-annotation)
```

```{r}
wastewater_clean = wastewater %>%
  mutate(population = parse_number(population),
         concentration = parse_number(concentration),
         date = mdy(sample_date)) %>%
  filter(!is.na(population),
         !is.na(concentration),
         !is.na(date)) %>%
  select(date, wrrf, concentration, population) %>%
  mutate(log_population = log(population))
```

```{r}
# Create a descriptive_table
descriptive_table = wastewater_clean %>%
  select(-date) %>%
   gtsummary::tbl_summary(type = all_continuous() ~ "continuous2",
                          statistic = list(all_continuous2() ~ c("{mean} ({sd})", "{min} - {max}"),
                                          all_categorical() ~ "{n}, {p}%"))
descriptive_table
```

```{r}
# Scatter plot of concentration versus time
con_time_plot = wastewater_clean %>%
  ggplot(aes(x = date, y = concentration)) +
  geom_point(alpha = 0.6) +
  geom_smooth() +
  theme_bw() +
  labs(title = "Scatter plot of concentration versus time",
       x= "Date",
       y = "Concentration") +
  scale_y_continuous(limits = c(0, 1250000))
con_time_plot
```

```{r}
# Scatter plot of concentration versus population
con_pop_plot = wastewater_clean %>%
  group_by(population) %>%
  summarize(mean_concentration = mean(concentration)) %>%
  ggplot(aes(x = population, y = mean_concentration)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = TRUE) +
  theme_bw() +
  labs(title = "Scatter plot of concentration versus population",
       x = "Population",
       y = "Concentration")
con_pop_plot
```

```{r}
# Correlation test
cor_test = cor.test(wastewater_clean$population,
                    wastewater_clean$concentration,
                    method = "pearson")
cor_test
cor_test$estimate
cor_test$p.value
cor_test$conf.int
```

```{r}
model1 = lm(concentration ~ population, data = wastewater_clean)
summary(model1)
model_results <- tidy(model1, conf.int = TRUE)

knitr::kable(model_results, digits = 3)
```

